# (C) 2010 University of Washington.
# The software is subject to an academic license.
# Terms are contained in the LICENSE file.

DMP_RUNTIME_FILES = [ 'library-barrier.cpp',
                      'library-cv.cpp',
                      'library-mutex.cpp',
                      'library-once.cpp',
                      'library-rwlock.cpp',
                      'library-semaphore.cpp',
                      'library-thread.cpp',
                      'runtime-main.cpp',
                      'runtime-model-B_S.cpp',
                      'runtime-model-O_S.cpp',
                      'runtime-model-OB_S.cpp',
                      'runtime-model-O_B_S.cpp',
                      'runtime-model-STM.cpp',
                      'runtime-profiling.cpp',
                      'runtime-sched.cpp',
                      'runtime-wb.cpp',
                      'debug.cpp' ]

Return('DMP_RUNTIME_FILES')
