#ifndef _BC_ASYNC_CONTROL_H_
#define _BC_ASYNC_CONTROL_H_

#define BC_COUNT_ACTIONS 0
#define BC_COUNT_LEAVES 0

#define BC_CONCURRENT 1
#define BC_USE_MARKING 1

#define VERBOSE_GRAPH_READ 0 
#define DOCHECKS 0

#endif // end BC_ASYNC_CONTROL
