---
files: ^libcusp|^libdeepgalois|^libdist|^libgalois|^libgluon|^libgnn|^libwmd
exclude: ^scripts|^python|^inputs
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: forbid-tabs
        exclude: ^scripts|^python
      - id: remove-tabs
        exclude: ^scripts|^python
        args: [--whitespaces-count, '2']
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]
      # - id: clang-tidy
      #   args: [--fix, -p=build/compile_commands.json]
