#include "galois/runtime/SyncStructures.h"

GALOIS_SYNC_STRUCTURE_REDUCE_ADD(nout, unsigned int);
GALOIS_SYNC_STRUCTURE_BROADCAST(nout, unsigned int);
GALOIS_SYNC_STRUCTURE_BITSET(nout);

GALOIS_SYNC_STRUCTURE_REDUCE_ADD(residual, float);
GALOIS_SYNC_STRUCTURE_REDUCE_SET(residual, float);
GALOIS_SYNC_STRUCTURE_BROADCAST(residual, float);
GALOIS_SYNC_STRUCTURE_BITSET(residual);

GALOIS_SYNC_STRUCTURE_REDUCE_MAX(value, float);
GALOIS_SYNC_STRUCTURE_BROADCAST(value, float);
