// Hoard version X.Y.0 = X0Y00

#define HOARD_MAJOR 3
#define HOARD_MINOR 8
#define HOARD_PATCH 0

#define HOARD_VERSION_STRING "3.8.0"
#define HOARD_VERSION_NUMBER (HOARD_MAJOR * 10000 + HOARD_MINOR * 100 + HOARD_PATCH)
