#ifndef __NPOSITION_3D_H_INCLUDED__
#define __NPOSITION_3D_H_INCLUDED__
enum
{
	LEFT2, RIGHT2, TOP2, BOT2, NEAR, FAR, TOP_LEFT, TOP_RIGHT, TOP_NEAR, TOP_FAR, BOT_LEFT, BOT_RIGHT, BOT_NEAR, BOT_FAR, LEFT_NEAR, LEFT_FAR, RIGHT_NEAR, RIGHT_FAR
};
#endif
