#!/bin/bash
PINBASE=/net/faraday/workspace/ddn/pin-2.11-49306-gcc.3.4.6-ia32_intel64-linux
PINTOOL=$PINBASE/source/tools/SimpleExamples/obj-intel64/atomiccount_vregs.so
OUT=atomiccount.$$
MAGIC=55
CMD="$PINBASE/pin -follow-execv -t $PINTOOL -o $OUT"

$CMD -- $*
R=$?
rm -f $OUT
if (( $R )); then
  exit $R
fi

GALOIS_EXIT_BEFORE_SAMPLING=$MAGIC $CMD -- $* 2>&1 > /dev/null
R=$?
if (( $R != $MAGIC )); then
  if [[ -f $OUT ]]; then
    cat $OUT
  fi
  rm -f $OUT
  exit $R
else
  if [[ -f $OUT ]]; then
    cat $OUT | sed 's/^/BEFORE/;'
  fi
  rm -f $OUT
fi

GALOIS_EXIT_AFTER_SAMPLING=$MAGIC $CMD -- $* 2>&1 > /dev/null
R=$?
if (( $R != $MAGIC )); then
  if [[ -f $OUT ]]; then
    cat $OUT
  fi
  rm -f $OUT
  exit $R
else
  if [[ -f $OUT ]]; then
    cat $OUT | sed 's/^/AFTER/;'
  fi
  rm -f $OUT
fi
