# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# HAVE_HUGEPAGES_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_HUGEPAGES_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The HAVE_HUGEPAGES_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /g/g14/nguyen91/build/default/CMakeFiles/CMakeTmp/src.c
# Executable    : /g/g14/nguyen91/build/default/CMakeFiles/cmTryCompileExec124295678-HAVE_HUGEPAGES_EXITCODE
# Run arguments : 
#    Called from: [2]	/g/g14/nguyen91/w/GaloisDefault/cmake/Modules/CheckHugePages.cmake
#                 [1]	/g/g14/nguyen91/w/GaloisDefault/CMakeLists.txt

SET( HAVE_HUGEPAGES_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

