/** Type Magic -*- C++ -*-
 * @file
 * @section License
 *
 * Galois, a framework to exploit amorphous data-parallelism in irregular
 * programs.
 *
 * Copyright (C) 2013, The University of Texas at Austin. All rights reserved.
 * UNIVERSITY EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS
 * SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR ANY PARTICULAR PURPOSE, NON-INFRINGEMENT AND WARRANTIES OF
 * PERFORMANCE, AND ANY WARRANTY THAT MIGHT OTHERWISE ARISE FROM COURSE OF
 * DEALING OR USAGE OF TRADE.  NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH
 * RESPECT TO THE USE OF THE SOFTWARE OR DOCUMENTATION. Under no circumstances
 * shall University be liable for incidental, special, indirect, direct or
 * consequential damages or loss of profits, interruption of business, or
 * related expenses which may arise from use of Software or Documentation,
 * including but not limited to those resulting from defects in Software and/or
 * Documentation, or loss or inaccuracy of data of any kind.
 *
 * @section Description
 *
 * Implement type meta-programming stuff
 *
 * @author Andrew Lenharth <andrewl@lenharth.org>
 */

#ifndef GALOIS_RUNTIME_TYPEMAGIC_H
#define GALOIS_RUNTIME_TYPEMAGIC_H

#include <tuple>
#include <type_traits>
#include <cstddef>

namespace Galois {
namespace Runtime {

// Cons a type onto a tuple
template <typename, typename> struct Cons;

template <typename  T, typename ...Args>
struct Cons<T, std::tuple<Args...>>
{
    using type = std::tuple<T, Args...>;
};

//Filter types into a tuple
template <template <typename> class, typename...> struct typeFilter;

template<template< typename> class Pred> struct typeFilter<Pred> { using type = std::tuple<>; };

template < template <typename> class Pred, typename Head, typename... Tail>
struct typeFilter<Pred, Head, Tail...>
{
  using type = typename std::conditional<Pred<Head>::value,
					 typename Cons<Head, typename typeFilter<Pred,Tail...>::type>::type,
					 typename typeFilter<Pred,Tail...>::type
					 >::type;
};

//apply a map to types
template < template <typename> class fMap, typename... Types>
struct typeMap
{
  using type = std::tuple<typename fMap<Types>::type...>;
};

//apply a map to types in a tuple
template < template <typename> class, typename...> struct typeTupleMap;
template < template <typename> class fMap, typename... Types>
struct typeTupleMap<fMap, std::tuple<Types...>>
{
  using type = typename typeMap<fMap, Types...>::type;
};


//apply a tuple of args to a function of args
//From Paul Preney
namespace detail {

template <std::size_t...>
struct indices { };

//Generate an integer type sequence
template <std::size_t Begin, std::size_t End, typename Indices = indices<>, typename Enable = void>
struct make_seq_indices {
  static_assert(Begin <= End, "Begin must be <= End");
};

template < std::size_t Begin, std::size_t End, template <std::size_t...> class I, std::size_t... Indices>
struct make_seq_indices<Begin, End, I<Indices...>, typename std::enable_if<Begin < End, void>::type > {
  using type = typename make_seq_indices<Begin+1, End, I<Indices..., Begin> >::type;
};

template <std::size_t Begin, std::size_t End, typename Indices>
struct make_seq_indices<Begin, End, Indices, typename std::enable_if<Begin == End, void>::type> {
  using type = Indices;
};

//type alias to simplify use
template <std::size_t Begin, std::size_t End>
using make_seq_indices_T = typename make_seq_indices<Begin, End>::type;

// This function overload applies op to all tuple indices...
template <typename Op, typename Tuple, template <std::size_t...> class I, std::size_t... Indices>
inline constexpr auto apply_tuple(Op&& op, Tuple&& t, I<Indices...>&&) -> 
  decltype(std::forward<Op>(op)(std::get<Indices>(std::forward<Tuple>(t))...)) {
  return std::forward<Op>(op)(std::get<Indices>(std::forward<Tuple>(t))...);
}
} // namespace detail

//appy a set of arguments to a function
template <typename Op, typename... Args>
inline constexpr auto apply_fn(Op&& op, Args&&... args) ->
  decltype(std::forward<Op>(op)(std::forward<Args>(args)...)) {
  return std::forward<Op>(op)(std::forward<Args>(args)...);
}

// This function overload forwards op and t along with the
// indices of the tuple generated by make_seq_indices...
template <typename Op, typename Tuple,
	  typename Indices = detail::make_seq_indices_T<0, std::tuple_size<typename std::decay<Tuple>::type>::value>>
inline constexpr auto apply_tuple(Op&& op, Tuple&& t) -> 
  decltype(detail::apply_tuple(std::forward<Op>(op), std::forward<Tuple>(t),Indices{})) {
  return detail::apply_tuple(std::forward<Op>(op), std::forward<Tuple>(t),Indices{} );
}

} // namespace Runtime
} // namespace Galois

#endif
