include(CheckLibraryExists)
CHECK_LIBRARY_EXISTS(numa numa_available "" LIBNUMA_FOUND_INTERNAL)
if(LIBNUMA_FOUND_INTERNAL)
  CHECK_LIBRARY_EXISTS(numa numa_allocate_nodemask "" LIBNUMA_NEW_INTERNAL)
  if(NOT LIBNUMA_NEW_INTERNAL)
    set(LIBNUMA_OLD "yes")
  endif()
endif()
find_package_handle_standard_args(LIBNUMA DEFAULT_MSG LIBNUMA_FOUND_INTERNAL)
