set(VTUNE_ROOTS "/opt/intel/vtune_amplifier_xe_2013;/opt/intel/vtune_amplifier_xe_2011")
set(VTUNE_FOUND off)
set(VTUNE_INCLUDE_DIRS off)
set(VTUNE_FOUND_INTERNAL off)

foreach (_dir ${VTUNE_ROOTS})
  if(NOT VTUNE_FOUND_INTERNAL)
    if(EXISTS "${_dir}/include")
      set(VTUNE_FOUND_INTERNAL "YES")
      set(VTUNE_LIBRARIES "${_dir}/lib64/libittnotify.a" dl)
      set(VTUNE_INCLUDE_DIRS "${_dir}/include")
    endif()
  endif()
endforeach()

find_package_handle_standard_args(VTUNE DEFAULT_MSG VTUNE_FOUND_INTERNAL)
