
#ifndef __EPOSITION_H_INCLUDED__
#define __EPOSITION_H_INCLUDED__
namespace tmp{
enum EPosition { BOT_LEFT_FAR, BOT_LEFT_NEAR, TOP_LEFT_FAR, TOP_LEFT_NEAR,
	TOP_RIGHT_FAR, TOP_RIGHT_NEAR, BOT_RIGHT_FAR, BOT_RIGHT_NEAR };
}
#endif
