name: C/C++ CI

on:
  push:
  pull_request:
    types:
    - created
    - synchronize

jobs:
  ###################################################################
  # lint
  ###################################################################
  lint:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        build_type:
        - Debug
    steps:
    - uses: actions/checkout@v2

    ###
    # Caching between builds
    ###
    - name: Cache conan packages
      uses: actions/cache@v1
      with:
        key: ${{runner.os}}-conan-${{hashFiles('config/conanfile.txt')}}
        path: ~/.conan/data
    - name: Cache ccache objects
      uses: actions/cache@v1
      with:
        key: ${{runner.os}}-ccache-${{matrix.build_type}}
        restore-keys: |
          ${{runner.os}}-ccache-
        path: ~/.ccache

    ###
    # Install platform-level dependencies (OS-specific)
    ###
    - name: install dependencies
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        sudo apt install -yq ccache curl gcc-9 g++-9 libopenmpi-dev
        sudo update-alternatives --verbose --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
        sudo update-alternatives --verbose --install /usr/bin/g++ g++ /usr/bin/g++-9 90

        sudo apt-add-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        curl -fL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt update
        sudo apt install -yq clang-format-10 clang-tidy-10

        sudo update-alternatives --verbose --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-10 90
        sudo update-alternatives --verbose --install /usr/bin/clang-format clang-format /usr/bin/clang-format-10 90

        clang-format --version
        clang-tidy --version

        sudo -H pip3 install --upgrade pip setuptools
        sudo -H pip3 install conan==1.22.3

        conan profile new --detect --force default
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: pre-build
      run: mkdir -p ~/build
    - name: install C++ dependencies
      run: |
        conan remote add kmaragon https://api.bintray.com/conan/kmaragon/conan
        conan install -if ~/build --build=missing config

    - name: check formating
      run: scripts/check_format.sh . || true  # Ignore formatting errors for now.

    ###
    # Standard CMake build process
    ###
    - name: configure
      run: |
        cmake -S . -B ~/build \
          -DCMAKE_INSTALL_PREFIX=/tmp \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DCMAKE_INSTALL_PREFIX=/tmp \
          -DCMAKE_TOOLCHAIN_FILE=~/build/conan_paths.cmake \
          -DCXX_CLANG_TIDY=clang-tidy \
          -DENABLE_DIST_GALOIS=on
    - name: build
      run: cmake --build ~/build --parallel 4

  ###################################################################
  # build_and_test
  ###################################################################
  build_and_test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - macOS-latest
        build_type:
        - Debug
        - Release
    steps:
    - uses: actions/checkout@v2

    ###
    # Caching between builds
    ###
    - name: Cache conan packages
      uses: actions/cache@v1
      with:
        key: ${{runner.os}}-conan-${{hashFiles('config/conanfile.txt')}}
        path: ~/.conan/data
    - name: Cache ccache objects
      uses: actions/cache@v1
      with:
        key: ${{runner.os}}-ccache-${{matrix.build_type}}
        restore-keys: |
          ${{runner.os}}-ccache-
        path: ~/.ccache

    ###
    # Install platform-level dependencies (OS-specific)
    ###
    - name: install dependencies
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        sudo apt install -yq ccache curl gcc-9 g++-9 libopenmpi-dev
        sudo update-alternatives --verbose --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
        sudo update-alternatives --verbose --install /usr/bin/g++ g++ /usr/bin/g++-9 90

        sudo -H pip3 install --upgrade pip setuptools
        sudo -H pip3 install conan==1.22.3

        conan profile new --detect --force default
        conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: install dependencies
      if: startsWith(matrix.os, 'macOS-')
      run: |
        brew install ccache conan openmpi
        conan profile new --detect --force default

    - name: pre-build
      run: mkdir -p ~/build
    - name: install C++ dependencies
      run: |
        conan remote add kmaragon https://api.bintray.com/conan/kmaragon/conan
        conan install -if ~/build --build=missing config

    ###
    # Standard CMake build process
    ###
    - name: configure
      run: |
        cmake -S . -B ~/build \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_INSTALL_PREFIX=/tmp \
          -DCMAKE_TOOLCHAIN_FILE=~/build/conan_paths.cmake \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DENABLE_DIST_GALOIS=on
    - name: build
      run: cmake --build ~/build --parallel 4
    - name: install
      run: cmake --install ~/build
    - name: test
      run: make -C ~/build test || true  # Ignore test errors for now.
